services:
  educateapi:
    build:
      context: EducateAPI.LoadGPTService/EducateAPI.LoadGPTService/
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTIFICATE_PASSWORD}
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/EducateAPI.LoadGPTService.pfx
      OPEN_API_KEY: ${OPEN_API_KEY}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${USER_PATH}\.aspnet\https\EducateAPI.LoadGPTService.pfx:/https/EducateAPI.LoadGPTService.pfx:ro
      - ${USER_PATH}\AppData\Roaming\microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USER_PATH}\.aspnet\https:/root/.aspnet/https/:ro
    depends_on:
      rabbitmq:
          condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      # start_period: 30s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
